// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TequliasResturant.Data;

#nullable disable

namespace TequliasResturant.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260709182335_ExpandedMenuSeedData")]
    partial class ExpandedMenuSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TequliasResturant.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TequliasResturant.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "Shareable starters and snacks.",
                            Name = "Appetizers"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "Tacos, enchiladas, burritos, and house plates.",
                            Name = "Entrees"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "Small extras to round out a meal.",
                            Name = "Sides"
                        },
                        new
                        {
                            CategoryId = 4,
                            Description = "Sweet finishes from the kitchen.",
                            Name = "Desserts"
                        },
                        new
                        {
                            CategoryId = 5,
                            Description = "Refreshing drinks and aguas frescas.",
                            Name = "Beverages"
                        });
                });

            modelBuilder.Entity("TequliasResturant.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngredientId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IngredientId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            IngredientId = 1,
                            Description = "Seasoned ground beef or steak.",
                            Name = "Beef"
                        },
                        new
                        {
                            IngredientId = 2,
                            Description = "Grilled or shredded chicken.",
                            Name = "Chicken"
                        },
                        new
                        {
                            IngredientId = 3,
                            Description = "Crispy white fish.",
                            Name = "Fish"
                        },
                        new
                        {
                            IngredientId = 4,
                            Description = "Soft corn tortilla.",
                            Name = "Corn Tortilla"
                        },
                        new
                        {
                            IngredientId = 5,
                            Description = "Large grilled flour tortilla.",
                            Name = "Flour Tortilla"
                        },
                        new
                        {
                            IngredientId = 6,
                            Description = "Crisp shredded lettuce.",
                            Name = "Lettuce"
                        },
                        new
                        {
                            IngredientId = 7,
                            Description = "Fresh tomato for pico and toppings.",
                            Name = "Tomato"
                        },
                        new
                        {
                            IngredientId = 8,
                            Description = "Fresh chopped cilantro.",
                            Name = "Cilantro"
                        },
                        new
                        {
                            IngredientId = 9,
                            Description = "Diced white onion.",
                            Name = "Onion"
                        },
                        new
                        {
                            IngredientId = 10,
                            Description = "Melted cheese or cotija.",
                            Name = "Cheese"
                        },
                        new
                        {
                            IngredientId = 11,
                            Description = "Mexican crema.",
                            Name = "Crema"
                        },
                        new
                        {
                            IngredientId = 12,
                            Description = "Fresh avocado guacamole.",
                            Name = "Guacamole"
                        },
                        new
                        {
                            IngredientId = 13,
                            Description = "Red chile salsa.",
                            Name = "Salsa Roja"
                        },
                        new
                        {
                            IngredientId = 14,
                            Description = "Green tomatillo salsa.",
                            Name = "Salsa Verde"
                        },
                        new
                        {
                            IngredientId = 15,
                            Description = "Mexican rice.",
                            Name = "Rice"
                        },
                        new
                        {
                            IngredientId = 16,
                            Description = "Pinto or refried beans.",
                            Name = "Beans"
                        },
                        new
                        {
                            IngredientId = 17,
                            Description = "Crispy corn chips.",
                            Name = "Tortilla Chips"
                        },
                        new
                        {
                            IngredientId = 18,
                            Description = "Sliced jalapenos.",
                            Name = "Jalapeno"
                        },
                        new
                        {
                            IngredientId = 19,
                            Description = "Warm cinnamon spice.",
                            Name = "Cinnamon"
                        },
                        new
                        {
                            IngredientId = 20,
                            Description = "Chocolate dipping sauce.",
                            Name = "Chocolate"
                        },
                        new
                        {
                            IngredientId = 21,
                            Description = "Fresh lime wedges or juice.",
                            Name = "Lime"
                        },
                        new
                        {
                            IngredientId = 22,
                            Description = "Cinnamon rice drink base.",
                            Name = "Horchata"
                        },
                        new
                        {
                            IngredientId = 23,
                            Description = "Hibiscus agua fresca.",
                            Name = "Jamaica"
                        });
                });

            modelBuilder.Entity("TequliasResturant.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TequliasResturant.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("TequliasResturant.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 2,
                            Description = "Three corn tortilla tacos with seasoned beef, onion, cilantro, salsa roja, and lime.",
                            ImageUrl = "/images/menu/tacos.png",
                            Name = "Beef Street Tacos",
                            Price = 8.99m,
                            Stock = 65
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 2,
                            Description = "Grilled chicken tacos with lettuce, pico de gallo, crema, and cotija cheese.",
                            ImageUrl = "/images/menu/tacos.png",
                            Name = "Chicken Tacos",
                            Price = 8.49m,
                            Stock = 70
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 2,
                            Description = "Crispy fish tacos with cabbage slaw, lime crema, pico de gallo, and salsa verde.",
                            ImageUrl = "/images/menu/tacos.png",
                            Name = "Baja Fish Tacos",
                            Price = 9.99m,
                            Stock = 45
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 2,
                            Description = "Two chicken enchiladas covered in red chile sauce, melted cheese, crema, rice, and beans.",
                            ImageUrl = "/images/menu/enchiladas.png",
                            Name = "Chicken Enchiladas",
                            Price = 11.99m,
                            Stock = 40
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 2,
                            Description = "Cheese and roasted vegetable enchiladas with salsa verde, crema, rice, and beans.",
                            ImageUrl = "/images/menu/enchiladas.png",
                            Name = "Veggie Enchiladas",
                            Price = 10.99m,
                            Stock = 35
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 2,
                            Description = "Large flour tortilla filled with steak, rice, beans, cheese, pico, guacamole, and salsa.",
                            ImageUrl = "/images/menu/tacos.png",
                            Name = "Carne Asada Burrito",
                            Price = 12.49m,
                            Stock = 38
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 1,
                            Description = "Tortilla chips with queso, beans, pico, jalapenos, sour cream, guacamole, and salsa.",
                            ImageUrl = "/images/menu/nachos.png",
                            Name = "Loaded Nachos",
                            Price = 9.49m,
                            Stock = 55
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 1,
                            Description = "Grilled flour tortilla with chicken and melted cheese, served with salsa and crema.",
                            ImageUrl = "/images/menu/quesadilla.png",
                            Name = "Chicken Quesadilla",
                            Price = 8.99m,
                            Stock = 50
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 1,
                            Description = "Warm tortilla chips with salsa roja, salsa verde, and pico de gallo.",
                            ImageUrl = "/images/menu/nachos.png",
                            Name = "Chips and Salsa Trio",
                            Price = 5.99m,
                            Stock = 80
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 3,
                            Description = "Savory tomato rice with garlic, onion, and cilantro.",
                            ImageUrl = "/images/menu/enchiladas.png",
                            Name = "Mexican Rice",
                            Price = 3.49m,
                            Stock = 90
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 3,
                            Description = "Creamy pinto beans finished with cotija cheese.",
                            ImageUrl = "/images/menu/enchiladas.png",
                            Name = "Refried Beans",
                            Price = 3.49m,
                            Stock = 85
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 4,
                            Description = "Cinnamon sugar churros served with warm chocolate dipping sauce.",
                            ImageUrl = "/images/menu/churros.png",
                            Name = "Churros",
                            Price = 5.49m,
                            Stock = 45
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 5,
                            Description = "Creamy cinnamon rice drink served cold.",
                            ImageUrl = "/images/menu/drinks.png",
                            Name = "Horchata",
                            Price = 3.49m,
                            Stock = 60
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 5,
                            Description = "Three small seasonal aguas frescas: jamaica, lime, and horchata.",
                            ImageUrl = "/images/menu/drinks.png",
                            Name = "Agua Fresca Flight",
                            Price = 5.99m,
                            Stock = 40
                        });
                });

            modelBuilder.Entity("TequliasResturant.Models.ProductIngredient", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("ProductIngredients");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            IngredientId = 1
                        },
                        new
                        {
                            ProductId = 1,
                            IngredientId = 4
                        },
                        new
                        {
                            ProductId = 1,
                            IngredientId = 8
                        },
                        new
                        {
                            ProductId = 1,
                            IngredientId = 9
                        },
                        new
                        {
                            ProductId = 1,
                            IngredientId = 13
                        },
                        new
                        {
                            ProductId = 1,
                            IngredientId = 21
                        },
                        new
                        {
                            ProductId = 2,
                            IngredientId = 2
                        },
                        new
                        {
                            ProductId = 2,
                            IngredientId = 4
                        },
                        new
                        {
                            ProductId = 2,
                            IngredientId = 6
                        },
                        new
                        {
                            ProductId = 2,
                            IngredientId = 7
                        },
                        new
                        {
                            ProductId = 2,
                            IngredientId = 10
                        },
                        new
                        {
                            ProductId = 2,
                            IngredientId = 11
                        },
                        new
                        {
                            ProductId = 3,
                            IngredientId = 3
                        },
                        new
                        {
                            ProductId = 3,
                            IngredientId = 4
                        },
                        new
                        {
                            ProductId = 3,
                            IngredientId = 6
                        },
                        new
                        {
                            ProductId = 3,
                            IngredientId = 11
                        },
                        new
                        {
                            ProductId = 3,
                            IngredientId = 14
                        },
                        new
                        {
                            ProductId = 3,
                            IngredientId = 21
                        },
                        new
                        {
                            ProductId = 4,
                            IngredientId = 2
                        },
                        new
                        {
                            ProductId = 4,
                            IngredientId = 4
                        },
                        new
                        {
                            ProductId = 4,
                            IngredientId = 10
                        },
                        new
                        {
                            ProductId = 4,
                            IngredientId = 11
                        },
                        new
                        {
                            ProductId = 4,
                            IngredientId = 13
                        },
                        new
                        {
                            ProductId = 4,
                            IngredientId = 15
                        },
                        new
                        {
                            ProductId = 4,
                            IngredientId = 16
                        },
                        new
                        {
                            ProductId = 5,
                            IngredientId = 4
                        },
                        new
                        {
                            ProductId = 5,
                            IngredientId = 10
                        },
                        new
                        {
                            ProductId = 5,
                            IngredientId = 11
                        },
                        new
                        {
                            ProductId = 5,
                            IngredientId = 14
                        },
                        new
                        {
                            ProductId = 5,
                            IngredientId = 15
                        },
                        new
                        {
                            ProductId = 5,
                            IngredientId = 16
                        },
                        new
                        {
                            ProductId = 6,
                            IngredientId = 1
                        },
                        new
                        {
                            ProductId = 6,
                            IngredientId = 5
                        },
                        new
                        {
                            ProductId = 6,
                            IngredientId = 7
                        },
                        new
                        {
                            ProductId = 6,
                            IngredientId = 10
                        },
                        new
                        {
                            ProductId = 6,
                            IngredientId = 12
                        },
                        new
                        {
                            ProductId = 6,
                            IngredientId = 13
                        },
                        new
                        {
                            ProductId = 6,
                            IngredientId = 15
                        },
                        new
                        {
                            ProductId = 6,
                            IngredientId = 16
                        },
                        new
                        {
                            ProductId = 7,
                            IngredientId = 10
                        },
                        new
                        {
                            ProductId = 7,
                            IngredientId = 12
                        },
                        new
                        {
                            ProductId = 7,
                            IngredientId = 13
                        },
                        new
                        {
                            ProductId = 7,
                            IngredientId = 16
                        },
                        new
                        {
                            ProductId = 7,
                            IngredientId = 17
                        },
                        new
                        {
                            ProductId = 7,
                            IngredientId = 18
                        },
                        new
                        {
                            ProductId = 8,
                            IngredientId = 2
                        },
                        new
                        {
                            ProductId = 8,
                            IngredientId = 5
                        },
                        new
                        {
                            ProductId = 8,
                            IngredientId = 10
                        },
                        new
                        {
                            ProductId = 8,
                            IngredientId = 11
                        },
                        new
                        {
                            ProductId = 8,
                            IngredientId = 13
                        },
                        new
                        {
                            ProductId = 9,
                            IngredientId = 7
                        },
                        new
                        {
                            ProductId = 9,
                            IngredientId = 13
                        },
                        new
                        {
                            ProductId = 9,
                            IngredientId = 14
                        },
                        new
                        {
                            ProductId = 9,
                            IngredientId = 17
                        },
                        new
                        {
                            ProductId = 10,
                            IngredientId = 8
                        },
                        new
                        {
                            ProductId = 10,
                            IngredientId = 9
                        },
                        new
                        {
                            ProductId = 10,
                            IngredientId = 15
                        },
                        new
                        {
                            ProductId = 11,
                            IngredientId = 10
                        },
                        new
                        {
                            ProductId = 11,
                            IngredientId = 16
                        },
                        new
                        {
                            ProductId = 12,
                            IngredientId = 19
                        },
                        new
                        {
                            ProductId = 12,
                            IngredientId = 20
                        },
                        new
                        {
                            ProductId = 13,
                            IngredientId = 19
                        },
                        new
                        {
                            ProductId = 13,
                            IngredientId = 22
                        },
                        new
                        {
                            ProductId = 14,
                            IngredientId = 21
                        },
                        new
                        {
                            ProductId = 14,
                            IngredientId = 22
                        },
                        new
                        {
                            ProductId = 14,
                            IngredientId = 23
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TequliasResturant.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TequliasResturant.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TequliasResturant.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TequliasResturant.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TequliasResturant.Models.Order", b =>
                {
                    b.HasOne("TequliasResturant.Models.ApplicationUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TequliasResturant.Models.OrderItem", b =>
                {
                    b.HasOne("TequliasResturant.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TequliasResturant.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TequliasResturant.Models.Product", b =>
                {
                    b.HasOne("TequliasResturant.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TequliasResturant.Models.ProductIngredient", b =>
                {
                    b.HasOne("TequliasResturant.Models.Ingredient", "Ingredient")
                        .WithMany("ProductIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TequliasResturant.Models.Product", "Product")
                        .WithMany("ProductIngredients")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TequliasResturant.Models.ApplicationUser", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("TequliasResturant.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("TequliasResturant.Models.Ingredient", b =>
                {
                    b.Navigation("ProductIngredients");
                });

            modelBuilder.Entity("TequliasResturant.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("TequliasResturant.Models.Product", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("ProductIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
